FROM maven:3.8.4-openjdk-8 AS buildstage

WORKDIR /app

COPY . .

RUN mvn package

FROM openjdk:8 AS runstage

COPY --from=buildstage /app/target/backend-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

RUN adduser --system --group spring

USER spring

ENTRYPOINT ["java", "-jar", "backend-0.0.1-SNAPSHOT.jar"]
